//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaLamViec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CaLamViec()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int CaId { get; set; }
        public int NhanVienId { get; set; }
        public System.DateTime ThoiGianMoCa { get; set; }
        public Nullable<System.DateTime> ThoiGianChotCa { get; set; }
        public decimal TienDauCa { get; set; }
        public decimal TongThuTienMat { get; set; }
        public decimal TongThuChuyenKhoan { get; set; }
        public decimal TongThuThe { get; set; }
        public string GhiChuChotCa { get; set; }
        public string TrangThai { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
